<?php

namespace Database\Seeders;

use App\Models\Items;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    //Ferramenta(specific+skill), Componente(complent), Consumível(once), Utilidade(many)
    public function run()
    {
        $items = [

            [
                'id' => 1,
                'item_name' => 'Ábaco',
                'item_type' => 'Ferramenta',
                'description' => 'O ábaco é um instrumento de cálculo, formado por uma moldura com bastões ou arames paralelos, dispostos no sentido vertical, correspondentes cada um a uma posição digital (unidades, dezenas, etc.) e nos quais estão os elementos de contagem (fichas, bolas ou contas) que podem fazer-se deslizar livremente.',
                'cost' => '2po',
                'Weight' => '1k',
            ],
            [
                'id' => 2,
                'item_name' => 'Ácido (vidro)',
                'item_type' => 'Consumível',
                'description' => 'Usando uma ação, você pode despejar o conteúdo desse vidro em uma criatura a até 1,5 metro de você, ou arremessar o vidro a até 6 metros de distância, quebrando-o no impacto. Em ambos os casos, você deve realizar um ataque à distância contra uma criatura ou objeto, tratando o ácido como uma arma improvisada. Se acertar, o alvo sofre 2d6 de dano ácido',
                'cost' => '25po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 3,
                'item_name' => 'Água benta (frasco)',
                'item_type' => 'Consumível',
                'description' => 'Usando uma ação, você pode despejar o conteúdo desse vidro em uma criatura a até 1,5 metro de você, ou arremessar o vidro a até 6 metros de distância, quebrando-o no impacto. Em ambos os casos, você deve realizar um ataque à distância contra uma criatura alvo, tratando a água benta como uma arma improvisada. Se o alvo for um corruptor ou morto-vivo, ele sofre 2d6 de dano radiante.
                Um clérigo ou paladino pode criar água benta realizando um ritual especial. O ritual leva 1 hora para ser realizado, consome 25 po de prata em pó e exige que se gaste um espaço de magia de 1º nível.',
                'cost' => '25po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 4,
                'item_name' => 'Algemas',
                'item_type' => 'Utilidade',
                'description' => 'Estas algemas de metal podem prender uma criatura Pequena ou Média. Escapar das algemas exige sucesso em um teste de Destreza CD 20. Quebrá-las exige um teste de Força CD 20 bem-sucedido. Cada conjunto de algemas vem com uma chave. Sem a chave, uma criatura proficiente com ferramentas de ladrão pode abrir a fechadura das algemas com um sucesso em um teste de Destreza CD 15. As algemas tem 15 PA.',
                'cost' => '2po',
                'Weight' => '2k',
            ],
            [
                'id' => 5,
                'item_name' => 'Algibeira',
                'item_type' => 'Utilidade',
                'description' => 'Uma bolsa de pano ou couro que pode armazenar até 20 munições de funda ou 50 munições de zarabatana, entre outras coisas para acesso rápido. Comporta até 15cm³ /3kg de equipamentos',
                'cost' => '5po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 6,
                'item_name' => 'Aljava',
                'item_type' => 'Utilidade',
                'description' => 'Uma aljava pode guardar até 20 flechas.',
                'cost' => '1po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 7,
                'item_name' => 'Ampulheta',
                'item_type' => 'Ferramenta',
                'description' => 'Ampulheta é um aparelho utilizado para medir a fração de um tempo, variando de tamanho proporcional a medição (minuto, hora, dia).',
                'cost' => '25po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 8,
                'item_name' => 'Antídoto (vidro)',
                'item_type' => 'Consumível',
                'description' => 'Uma criatura que beber o líquidos deste frasco adquire vantagem em testes de resistência contra venenos por 1 hora. O antídoto não confere nenhum benefício para mortos-vivos ou constructos.',
                'cost' => '50po',
                'Weight' => null,
            ],
            [
                'id' => 9,
                'item_name' => 'Apito de advertência',
                'item_type' => 'Ferramenta',
                'description' => 'Um Apito feito de madeira, usado para sinalização ou música.',
                'cost' => '25po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 10,
                'item_name' => 'Aríeteportátil',
                'item_type' => 'Ferramenta',
                'description' => 'O personagem pode usar um aríete portátil para quebrar portas. Ao fazer isso, o personagem ganha um bônus de +4 no teste de Força. Um outro personagem pode ajudá-lo a usar o aríete, o que lhe dá vantagem no teste.',
                'cost' => '4po',
                'Weight' => '17,5k',
            ],
            [
                'id' => 11,
                'item_name' => 'Armadilha de caça',
                'item_type' => 'Utilidade',
                'description' => 'Quando o personagem usa sua ação para armá-la, essa armadilha forma um anel de aço com dentes serrilhados que se fecha quando uma criatura pisa sobre uma placa de pressão no seu centro. A armadilha é fixada por uma pesada corrente em um objeto fixo e imóvel, como uma árvore ou um cravo enterrado no chão. Uma criatura que pisar na placa de pressão deve ser bem sucedida em um teste de resistência de Destreza CD 13 ou sofrerá 1d4 de dano perfurante e parará de se mover. Daí em diante, até que a criatura se liberte da armadilha, seu movimento é limitado ao comprimento da corrente (tipicamente 1 metro de comprimento). A criatura presa pode usar sua ação para realizar um teste de Força CD 13 e se libertar, ou outra criatura, ao alcance, pode realizar o teste para libertá-la. Cada fracasso no teste causa 1 de dano perfurante à criatura presa.',
                'cost' => '5po',
                'Weight' => '12,5k',
            ],
            [
                'id' => 12,
                'item_name' => 'Arpéu',
                'item_type' => 'Ferramenta',
                'description' => 'Um gancho de ferro semelhante a um anzol ou uma âncora. Normalmente fixado na ponta de uma longa haste de ferro, usada nas abordagens de navios. O arpel(sem a haste) também pode ser utilizado em conjunto com uma corda para facilitar na escalada de paredes e terrenos difíceis. Para isso o item deve ser amarrado em uma das extremidades da corda e lançado.',
                'cost' => '2po',
                'Weight' => '2k',
            ],
            [
                'id' => 13,
                'item_name' => 'Balança de mercador',
                'item_type' => 'Ferramenta',
                'description' => 'A régua inclui uma pequena balança, panelas e um sortimento adequado de pesos até 2 quilos. Com ela, o personagem pode medir o peso exato de pequenos objetos, como metais preciosos brutos ou bens comerciais, para ajudar a determinar seu valor.',
                'cost' => '5po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 14,
                'item_name' => 'Balde',
                'item_type' => 'Utilidade',
                'description' => 'Um balde de madeira reforçado com anéis de ferro, comporta até 12 litros/15cm³ sólido.',
                'cost' => '5pc',
                'Weight' => '1k',
            ],
            [
                'id' => 15,
                'item_name' => 'Barril',
                'item_type' => 'Utilidade',
                'description' => 'Um barril de madeira reforçado com anéis de ferro, comporta até 160 litros/1,2m³ sólido.',
                'cost' => '2po',
                'Weight' => '35k',
            ],
            [
                'id' => 16,
                'item_name' => 'Baú',
                'item_type' => 'Utilidade',
                'description' => 'Um baú de madeira enrigecida reforçado com hastes e pregos de ferro, comporta até 3,5m³ /150kg de equipamentos.',
                'cost' => '5po',
                'Weight' => '12,5k',
            ],
            [
                'id' => 17,
                'item_name' => 'Bolsa de componentes',
                'item_type' => 'Componente',
                'description' => 'A bolsa de componentes é uma pequena bolsa de couro à prova da água que pode ser fixada em um cinto, e que tem compartimentos para armazenar todos os componentes materiais e outros itens especiais que o personagem precisa para lançar suas magias, exceto os componentes que possuem um custo específico (conforme indicado na descrição da magia).',
                'cost' => '25po',
                'Weight' => '1k',
            ],
            [
                'id' => 18,
                'item_name' => 'Caixa de Fogo',
                'item_type' => 'Utilidade',
                'description' => 'Este pequeno recipiente detém uma pederneira, isqueiro e um pavio (um pano geralmente seco embebido em óleo) usado para acender uma fogueira. Usá-lo para acender uma tocha - ou qualquer outra coisa exposta à combustível abundante - leva uma ação. Acender qualquer outro fogo leva 1 minuto.',
                'cost' => '5pp',
                'Weight' => '0,5k',
            ],
            [
                'id' => 19,
                'item_name' => 'Caneca de cerveja',
                'item_type' => 'Utilidade',
                'description' => 'Uma caneca rústica feita de madeiro ou ferro, comporta até 500ml.',
                'cost' => '2pc',
                'Weight' => '0,5k',
            ],
            [
                'id' => 20,
                'item_name' => 'Caneta tinteiro',
                'item_type' => 'Utilidade',
                'description' => 'Uma caneta de corpo metalico com um pequeno reservatório interno para tinta.',
                'cost' => '2pc',
                'Weight' => null,
            ],
            [
                'id' => 21,
                'item_name' => 'Cantil',
                'item_type' => 'Utilidade',
                'description' => 'Um recipiente feito de couro de animal, selado por um anél de madeira ou ferro com uma rolha. Utilizado no transporte de líquidos diversos como água, azeite, manteiga e bebidas alcólicas. Comporta até 2 litros',
                'cost' => '2pp',
                'Weight' => '2,5k',
            ],
            [
                'id' => 22,
                'item_name' => 'Cesto',
                'item_type' => 'Utilidade',
                'description' => 'Um cesto feito de palha ou fibra, podendo ter braços ou tampa. Comporta até 60cm³ /20kg de equipamentos.',
                'cost' => '4pp',
                'Weight' => '1k',
            ],
            [
                'id' => 23,
                'item_name' => 'Cobertor de inverno',
                'item_type' => 'Utilidade',
                'description' => 'Manta acolchoada composta por camadas grossas de tecido.',
                'cost' => '5pp',
                'Weight' => '1,5k',
            ],
            [
                'id' => 24,
                'item_name' => 'Corda (15 metros)',
                'item_type' => 'Utilidade',
                'description' => 'A corda é feita de cânhamo ou de seda, tem 2 PV e pode arrebentar com um teste de Força CD 17 bem sucedido.',
                'cost' => '1po',
                'Weight' => '5k',
            ],
            [
                'id' => 25,
                'item_name' => 'Corrente (3 metros)',
                'item_type' => 'Utilidade',
                'description' => 'Uma corrente possui 10 PA, ela pode ser arrebentada com um sucesso em um teste de Força CD 20.',
                'cost' => '5po',
                'Weight' => '5k',
            ],
            [
                'id' => 26,
                'item_name' => 'Equipamento de pescaria',
                'item_type' => 'Ferramenta',
                'description' => 'Este kit inclui uma vara de pescar de madeira, linha de seda, bóias de cortiça, anzóis de aço, chumbadas, iscas, e redes de pesca.',
                'cost' => '1po',
                'Weight' => '2k',
            ],
            [
                'id' => 27,
                'item_name' => 'Escada (3 metros)',
                'item_type' => 'Utilidade',
                'description' => 'Escafeita de toras ou tábuas de madeira unida por cordas ou pregos.',
                'cost' => '1pp',
                'Weight' => '12,5k',
            ],
            [
                'id' => 28,
                'item_name' => 'Esferas (bolsa com 1,000)',
                'item_type' => 'Consumível',
                'description' => 'Usando uma ação, o personagem pode despejar essas minúsculas esferas de metal para cobrir uma área de 3 metros quadrados (2 quadrados). A criatura que se mover dentro da área deve ser bem sucedida em um teste de resistência de Destreza CD ou ficará derrubada. Uma criatura que se andar pela área usando metade do seu deslocamento não precisa realizar o teste de resistência.',
                'cost' => '1po',
                'Weight' => '1k',
            ],
            [
                'id' => 29,
                'item_name' => 'Esmeril',
                'item_type' => 'Ferramenta',
                'description' => 'Ferramenta utilizada para afiar ferramentas, tirar rebarbas de peças forjadas ou serradas, arredondar cantos de peças, desbastar, dar acabamento, remover ferrugem, polir, dentre outras.',
                'cost' => '1pc',
                'Weight' => '0,5k',
            ],
            [
                'id' => 30,
                'item_name' => 'Espelho de aço',
                'item_type' => 'Utilidade',
                'description' => 'Um pequeno espelho com costas de aço.',
                'cost' => '5po',
                'Weight' => '0,25k',
            ],
            [
                'id' => 31,
                'item_name' => 'Estrepes (bolsa com 20)',
                'item_type' => 'Consumível',
                'description' => 'Usando uma ação, o personagem pode espalhar um único saco de estrepes para cobrir uma área de 1,5 metros quadrados (1 quadrado). Qualquer criatura que entrar na área deve ser bem sucedida em um teste de resistência de Destreza CD 15 ou parar de se mover e sofrer 1 de dano perfurante. Até que a criatura recupere, pelo menos 1 ponto de vida, seu deslocamento de caminhada é reduzido em 3 metros (2 quadrados). Uma Criatura que se andar pela área usando metade do seu deslocamento não precisa realizar o teste de resistência.',
                'cost' => '1po',
                'Weight' => '1k',
            ],
            [
                'id' => 32,
                'item_name' => 'Fechadura',
                'item_type' => 'Utilidade',
                'description' => 'A fechadura vêm com chave. Sem a chave, uma criatura proficiente com ferramentas de ladrão pode abrir a fechadura com um sucesso em um teste de Destreza CD 15. O Mestre pode decidir que fechaduras melhores estão disponíveis por preços mais elevados.',
                'cost' => '10po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 33,
                'item_name' => 'Fogo alquímico (frasco)',
                'item_type' => 'Consumível',
                'description' => 'Este líquido pegajoso e adesivo inflama em contado com o ar. Usando uma ação, o personagem pode arremessar este frasco até 6 metros de distância (4 quadrados), quebrando-o com o impacto. O jogador deve realizar um ataque à distância contra a criatura ou objeto, tratando o fogo alquímico como uma arma improvisada. Em um sucesso, o alvo sofre 1d4 de dano flamejante no início de cada um de seus turnos. Uma criatura pode finalizar este dano usando sua ação para realizar um teste de Destreza CD 10 para apagar as chamas.',
                'cost' => '50po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 34,
                'item_name' => 'Garrafa de vidro',
                'item_type' => 'Utilidade',
                'description' => 'Uma garrafa de vidro fechada por rolha. Comporta até 750ml.',
                'cost' => '2pc',
                'Weight' => '1k',
            ],
            [
                'id' => 35,
                'item_name' => 'Giz (1 peça)',
                'item_type' => 'Consumível',
                'description' => 'Um pedaço de giz branco.',
                'cost' => '1pc',
                'Weight' => null,
            ],
            [
                'id' => 36,
                'item_name' => 'Grimório',
                'item_type' => 'Ferramenta',
                'description' => 'Essencial para os magos, um grimório é um volume encadernado em couro com 100 páginas de pergaminhos em branco adequados para gravar magias.',
                'cost' => '50po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 37,
                'item_name' => 'Foco Arcano',
                'item_type' => 'Complemento',
                'description' => 'Um foco arcano é um item especial –
                um orbe, um cristal, um bastão, um cajado especialmente
                construído, uma varinha de madeira, ou algum item
                semelhante – projetado para canalizar o poder de magias
                arcanas. Um feiticeiro, bruxo ou mago podem usá-lo como
                um foco de conjuração.
                - Bastão     10po     1k
                - Cajado     5po      2k
                - Cristal    10po     0,5k
                - Orbe       20po     1,5k
                - Varinha    10po     0,5k',
                'cost' => 'Variável',
                'Weight' => 'Variável',
            ],
            [
                'id' => 38,
                'item_name' => 'Foco Druidico',
                'item_type' => 'Complemento',
                'description' => 'Um implemento druídico pode ser um ramo de visco ou azevinho, uma varinha ou cetro feito de teixo ou de outra madeira especial, um cajado esculpido de uma árvore viva, ou um totem adornado com penas, peles, ossos e dentes de animais sagrados.
                - Cajado de madeira    5po      2k
                - Ramo de visco        1po      -
                - -Totem               1po      -
                - Varinha              10po     0,5k',
                'cost' => 'Variável',
                'Weight' => 'Variável',
            ],
            [
                'id' => 39,
                'item_name' => 'Jarro',
                'item_type' => 'Utilidade',
                'description' => 'Jarro feito de cerâmica, ferro ou madeira. Comporta até 4 litros.',
                'cost' => '4pc',
                'Weight' => '2k',
            ],
            [
                'id' => 40,
                'item_name' => 'Kit de escalada',
                'item_type' => 'Ferramenta',
                'description' => 'Um kit de escalada inclui pítons especiais, botas com solas pontiagudas, luvas e um cinto. O personagem pode usar o kit do escalada como uma ação para "ancorar-se"; quando o personagem faz isso, ele não pode cair mais de 7,5 metros (5 quadrados) a partir do ponto onde ancorou-se, e não pode subir mais de 7,5 metros (5 quadrados) de distância desse ponto, sem desfazer a âncora.',
                'cost' => '25po',
                'Weight' => '6k',
            ],
            [
                'id' => 41,
                'item_name' => 'Kit de primeiros socorros',
                'item_type' => 'Ferramenta',
                'description' => 'Este kit é uma bolsa de couro contendo ataduras, pomadas e talas. O kit tem dez usos. Usando uma ação, o personagem pode gastar um uso do kit para estabilizar uma criatura que tenha 0 PA, sem a necessidade de realizar um teste de Sabedoria (Medicina).',
                'cost' => '5po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 42,
                'item_name' => 'Kit de refeição',
                'item_type' => 'Ferramenta',
                'description' => 'Esta caixa de lata contém um copo e talheres simples. A caixa se desmonta no meio, um lado pode ser utilizado como uma panela para cozinhar e o outro como um prato ou uma tigela rasa.',
                'cost' => '2pp',
                'Weight' => '0,5k',
            ],
            [
                'id' => 43,
                'item_name' => 'Lâmpada',
                'item_type' => 'Ferramenta',
                'description' => 'Uma lâmpada lança luz brilhante em um raio de 4,5 metros (3 quadrados) e luz baixa por mais 9 metros (6 quadrados). Uma vez acesa, a lâmpada queima por 6 horas usando um frasco de óleo (500ml).',
                'cost' => '5pp',
                'Weight' => '0,5k',
            ],
            [
                'id' => 44,
                'item_name' => 'Lanterna coberta',
                'item_type' => 'Ferramenta',
                'description' => 'Uma lanterna coberta lança luz brilhante em um raio de 9 metros (6 quadrados) e luz baixa por mais 9 metros. Uma vez acesa, ela queima por 6 horas usando um frasco de óleo (500ml). Usando uma ação, o personagem pode abaixar a cobertura, reduzindo a luz brilhante para luz baixa em um raio de 1,5 metros (1 quadrado).',
                'cost' => '5po',
                'Weight' => '1k',
            ],
            [
                'id' => 45,
                'item_name' => 'Lanterna furta-fogo',
                'item_type' => 'Ferramenta',
                'description' => 'Uma lanterna furta fogo lança luz brilhante em um cone de 18 metros (16 quadrados) e luz baixa em mais 18 metros adicionais. Uma vez acesa, ela queima por 6 horas usando um frasco de óleo (500ml).',
                'cost' => '10po',
                'Weight' => '1k',
            ],
            [
                'id' => 46,
                'item_name' => 'Lente de aumento',
                'item_type' => 'Utilidade',
                'description' => 'Esta lente permite um olhar mais atento a pequenos objetos. Ela também é útil como um substituto para a pederneira e isqueiro ao iniciar fogos. Acender um fogo com uma lupa necessita de luz tão brilhante como a luz solar para focar, um pavio, e cerca de 5 minutos para o fogo para acender. Uma lente de aumento concede vantagem em qualquer teste de atributo realizado para avaliar ou inspecionar um item que é pequeno ou muito detalhado.',
                'cost' => '100po',
                'Weight' => null,
            ],
            [
                'id' => 47,
                'item_name' => 'Livro',
                'item_type' => 'Utilidade',
                'description' => 'Um livro pode conter poesia, relatos históricos, informações relativas a um campo particular de sabedoria, diagramas e notas sobre engenhocas de gnomos, ou qualquer outra coisa que possa ser representada usando texto ou imagens. Um livro com magias é um grimório.',
                'cost' => '25po',
                'Weight' => '2,5k',
            ],
            [
                'id' => 48,
                'item_name' => 'Luneta',
                'item_type' => 'Ferramenta',
                'description' => 'Objetos vistos através de uma luneta são ampliados até o dobro do seu tamanho.',
                'cost' => '1000po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 49,
                'item_name' => 'Manto',
                'item_type' => 'Utilidade',
                'description' => 'Capa longa com capuz feito de tecido groço, preso ao peito por uma fivela de ferro.',
                'cost' => '1po',
                'Weight' => '2k',
            ],
            [
                'id' => 50,
                'item_name' => 'Marreta',
                'item_type' => 'Ferramenta',
                'description' => 'Ferramenta com corpo de madeira e cabeça de ferro. Precisa ser usado com ambas as mãos devido sua proporção.',
                'cost' => '2po',
                'Weight' => '5k',
            ],
            [
                'id' => 51,
                'item_name' => 'Martelo',
                'item_type' => 'Ferramenta',
                'description' => 'Marreta de mão com corpo de madeira e cabeça de ferro.',
                'cost' => '1po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 52,
                'item_name' => 'Mochila',
                'item_type' => 'Ferramenta',
                'description' => 'Bolsa de couro Adornada de algibeiras, fivelas de couro e argolas de ferro. Comporta até 30cm³ /15kg de equipamentos',
                'cost' => '2po',
                'Weight' => '2,5k',
            ],
            [
                'id' => 53,
                'item_name' => 'Munição',
                'item_type' => 'Componente',
                'description' => 'O tipo de munição determina o custo por quantidade de cada uma.
                -Zarabatana (50)        1po     0,5k
                -Balas de Funda (20)    4pc     0,75k
                -Flechas (20)           1po     0,5k
                -Virotes (20)           1po     0,75k',
                'cost' => 'Variável',
                'Weight' => 'Variável',
            ],
            [
                'id' => 54,
                'item_name' => 'Óleo (frasco)',
                'item_type' => 'Consumível',
                'description' => 'Óleo geralmente vem em um frasco de argila que contém 500ml. Usando uma ação, o personagem pode espirrar o óleo deste frasco em uma criatura adjacente (1,5 metros ou 1quadrado) arremessar até 6 metros (4 quadrados), quebrando-o com o impacto. O jogador deve realizar um ataque à distância contra uma criatura ou objeto, tratando o óleo como uma arma improvisada. Em um sucesso, o alvo é coberto de óleo. Se o alvo sofrer qualquer dano flamejante antes do óleo secar (depois de 1minuto), ele sofre 5 de dano flamejante adicional pela queima do óleo. O personagem também pode derramar um frasco de óleo no chão para cobrir uma área de 1,5 metros quadrados (1quadrado), desde que a superfície esteja nivelada. Se aceso, o óleo queima por 2 rodadas e causa 5 de dano flamejante a qualquer criatura que entrar na área ou terminar seu turno dentro da área. Uma criatura pode sofrer esse dano apenas uma vez por turno.',
                'cost' => '1po',
                'Weight' => '1po',
            ],
            [
                'id' => 55,
                'item_name' => 'Pá',
                'item_type' => 'Ferramenta',
                'description' => 'Ferramenta de corpo de madeira e cabeça triangular reta ou concava, utilizada para cavar.',
                'cost' => '2po',
                'Weight' => '2,5k',
            ],
            [
                'id' => 56,
                'item_name' => 'Panela de ferro',
                'item_type' => 'Utilidade',
                'description' => 'Uma panela de ferro com baços de madeira e tampa de ferro. Comporta até 4 litros.',
                'cost' => '2po',
                'Weight' => '5k',
            ],
            [
                'id' => 57,
                'item_name' => 'Papel (uma folha)',
                'item_type' => 'Componente',
                'description' => 'Recorte retângular, normalmente feito uma fina camada de linho, algodão ou cânhamo.',
                'cost' => '2pp',
                'Weight' => null,
            ],
            [
                'id' => 58,
                'item_name' => 'Parafina ',
                'item_type' => 'Utilidade',
                'description' => 'Confeccionada a base água, cera de abelha, algum óleo. Normalmente usada para fazer velas.',
                'cost' => '5pp',
                'Weight' => null,
            ],
            [
                'id' => 59,
                'item_name' => 'Pé de cabra',
                'item_type' => 'Ferramenta',
                'description' => 'Usar um pé de cabra concede vantagem nos testes de Força, onde uma alavanca possa ser aplicada.',
                'cost' => '2po',
                'Weight' => '2,5k',
            ],
            [
                'id' => 60,
                'item_name' => 'Perfume (vidro)',
                'item_type' => 'Consumível',
                'description' => 'Solução erbal de haroma agradável. Normalmente feita de cera, óleos vegetais, gorduras e sabões de ervas variadas.',
                'cost' => '5po',
                'Weight' => null,
            ],
            [
                'id' => 61,
                'item_name' => 'Pergaminho (uma folha)',
                'item_type' => 'Componente',
                'description' => 'Recorte retângular feito de pele de animal tratada.',
                'cost' => '1pp',
                'Weight' => null,
            ],
            [
                'id' => 62,
                'item_name' => 'Picareta de mina',
                'item_type' => 'Ferramenta',
                'description' => 'Semelhante ao martelo que consiste em uma cabeça de metal pontiaguda fixada na ponta de um cabo comprido feito usualmente de madeira.',
                'cost' => '2po',
                'Weight' => '5k',
            ],
            [
                'id' => 63,
                'item_name' => 'Píton',
                'item_type' => 'Componente',
                'description' => 'Peça de metal usada em escalado para "âncorar" corda.',
                'cost' => '5pc',
                'Weight' => null,
            ],
            [
                'id' => 64,
                'item_name' => 'Poção de cura',
                'item_type' => 'Consumível',
                'description' => 'Um personagem que beber o líquido vermelho mágico deste frasco recupera 2d4+2 PV.',
                'cost' => '50po',
                'Weight' => '0,25k',
            ],
            [
                'id' => 65,
                'item_name' => 'Porta mapas ou pergaminhos',
                'item_type' => 'Utilidade',
                'description' => 'Este estojo cilíndrico de couro pode armazenar até 10 folhas de papel enroladas ou 5 folhas de pergaminhos enroladas.',
                'cost' => '1po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 66,
                'item_name' => 'Porta virotes de besta',
                'item_type' => 'Utilidade',
                'description' => 'Este estojo de madeira pode armazenar até 20 virotes de besta.',
                'cost' => '1po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 67,
                'item_name' => 'Pregos de ferro (10)',
                'item_type' => 'Consumível',
                'description' => 'Uma sacola de couro de pregos de ferro.',
                'cost' => '1po',
                'Weight' => '2,5k',
            ],
            [
                'id' => 68,
                'item_name' => 'Rações de viagem (1 dia)',
                'item_type' => 'Consumível',
                'description' => 'Rações de viajem consistem em alimentos secos adequados para viagens longas, incluindo carne seca, frutas secas, bolachas, e nozes.',
                'cost' => '5pp',
                'Weight' => '1k',
            ],
            [
                'id' => 69,
                'item_name' => 'Sabão',
                'item_type' => 'Utilidade',
                'description' => 'Composição sólida de gordura e óleos vegetais.',
                'cost' => '2pc',
                'Weight' => null,
            ],
            [
                'id' => 70,
                'item_name' => 'Saco',
                'item_type' => 'Utilidade',
                'description' => 'Saco de couro simples costurado com linho. Comporta até 30cm³ /13kg de equipamentos.',
                'cost' => '1pc',
                'Weight' => '0,25k',
            ],
            [
                'id' => 71,
                'item_name' => 'Saco de dormir',
                'item_type' => 'Utilidade',
                'description' => 'Um saco de dormir é composto de um colchão e uma coberta, finas o bastante para serem enroladas e amarradas. Numa emergência, pode servir como maca.',
                'cost' => '1po',
                'Weight' => '3,5k',
            ],
            [
                'id' => 72,
                'item_name' => 'Símbolo Sagrado',
                'item_type' => 'Componente',
                'description' => 'Um símbolo sagrado é uma representação de um deus ou panteão. Pode ser um amuleto representando o símbolo de uma divindade, o mesmo símbolo cuidadosamente gravado ou ornado como o emblema de um escudo, ou uma pequena caixa com um fragmento de uma relíquia sagrada.
                - Amuleto    5po      0,5k
                - Emblema    5po      -
                - Relicário  5po      1k',
                'cost' => 'Variável',
                'Weight' => 'Variável',
            ],
            [
                'id' => 73,
                'item_name' => 'Sinete',
                'item_type' => 'Ferramenta',
                'description' => 'Cada sinete possui um símbolo personalizado cravado. Quando pressionado sobre parafina aquecida, ele deixa uma marca ou lacre facilmente identificável.',
                'cost' => '5po',
                'Weight' => null,
            ],
            [
                'id' => 74,
                'item_name' => 'Sino',
                'item_type' => 'Utilidade',
                'description' => 'Um pequeno sino de ferro.',
                'cost' => '1po',
                'Weight' => null,
            ],
            [
                'id' => 75,
                'item_name' => 'Talha ou sisal',
                'item_type' => 'Ferramenta',
                'description' => 'Um conjunto de roldanas com um cabo entre elas e um gancho para fixar aos objetos, a talha ou sisal permite içar até quatro vezes o peso que um personagem poderia levantar normalmente.',
                'cost' => '1po',
                'Weight' => '2,5k
                ',
            ],
            [
                'id' => 76,
                'item_name' => 'Tenda para duas pessoas',
                'item_type' => 'Utilidade',
                'description' => 'Um abrigo simples e portátil, acomoda dois indivíduos.',
                'cost' => '2po',
                'Weight' => '10k',
            ],
            [
                'id' => 77,
                'item_name' => 'Tocha',
                'item_type' => 'Utilidade',
                'description' => 'A tocha queima por 1 hora, fornecendo luz brilhante num raio de 6 metros (4 quadrados) e luz baixa por mais 6 metros. Se o personagem realizar um ataque corpo a corpo com uma tocha.',
                'cost' => '1pc',
                'Weight' => '0,5k',
            ],
            [
                'id' => 78,
                'item_name' => 'Tinta (vidro de 30ml)',
                'item_type' => 'Consumível',
                'description' => 'Tinta preta. O personagem pode comprar outras cores, mas elas custam o dobro do preço indicado.',
                'cost' => '10po',
                'Weight' => null,
            ],
            [
                'id' => 79,
                'item_name' => 'Traje, comum',
                'item_type' => 'Utilidade',
                'description' => 'Esse conjunto de roupas consiste em uma camisa larga e calças soltas, uma saia ou um vestido. Um pano enrolado protege os pés no lugar dos sapatos.',
                'cost' => '5pp',
                'Weight' => '1,5k',
            ],
            [
                'id' => 80,
                'item_name' => 'Traje, elegante',
                'item_type' => 'Utilidade',
                'description' => 'Esse traje inclui roupas de luxo suntuosas, feitas sob medida com seda e peles em abundância e cores estravagantes, adequadas ao estilo da corte dos nobres. Influenciar nobres ou cortesões é uma tarefa difícil usando roupas comuns. Se estiver usando esse traje sem pelo menos uma jóia, o usuário parecerá um camponês tolo.',
                'cost' => '5po',
                'Weight' => '3k',
            ],
            [
                'id' => 81,
                'item_name' => 'Traje, fantasia',
                'item_type' => 'Utilidade',
                'description' => 'É um conjunto de roupas espalhafatosas para entreter as pessoas. Ainda que a roupa pareça tola, seu estilo confortável permite que o usuário realize acrobacias, dance, caminhe sobre a corda bamba ou simplesmente corra se a audiência ficar irritada.',
                'cost' => '15po',
                'Weight' => '2k',
            ],
            [
                'id' => 82,
                'item_name' => 'Traje, viajante',
                'item_type' => 'Utilidade',
                'description' => 'Esse traje é um conjunto de roupas adequadas para quem nunca sabe o que esperar. Inclui botas resistentes, calças ou saias de couro, um cinto, uma camisa (e talvez um colete ou jaqueta), luvas e uma capa. As roupas possuem vários bolsos (especialmente a capa). Ela também contém itens adicionais que pode ser úteis, como um cachecol ou um chapéu de aba larga.',
                'cost' => '2po',
                'Weight' => '2k',
            ],
            [
                'id' => 83,
                'item_name' => 'Vara (3 metros)',
                'item_type' => 'Utilidade',
                'description' => 'Uma longa haste de madeira.',
                'cost' => '5pc',
                'Weight' => '3,5k',
            ],
            [
                'id' => 84,
                'item_name' => 'Vela',
                'item_type' => 'Consumível',
                'description' => 'Por uma hora, a vela emana luz brilhante em uma área de 1,5 metros quadrados (1 quadrado), e luz baixa em uma área adicional de 1,5 metros quadrados (1 quadrado).',
                'cost' => '1pc',
                'Weight' => null,
            ],
            [
                'id' => 85,
                'item_name' => 'Veneno básico (vidro)',
                'item_type' => 'Consumível',
                'description' => 'O personagem pode usar o veneno contido neste vidro para cobrir a lâmina de uma arma cortante ou perfurante ou até três peças de munição. Aplicar o veneno leva uma ação. Uma criatura atingida pela arma ou munição envenenada deve obter sucesso em um teste de resistência de Constituição CD 10 ou sofrerá 1d4 de dano venenoso. Uma vez aplicado, o veneno retém sua potência durante 1minuto antes da secar.',
                'cost' => '100po',
                'Weight' => null,
            ],
            [
                'id' => 86,
                'item_name' => 'Vidro ou frasco',
                'item_type' => 'Consumível',
                'description' => 'Um pequeno recipiente feito de vidro, com uma rolha de tampa. Frascos tendem a ser mais rígidos e duráveis enquanto vidros mais finos e frágeis. Comportam até 30ml de solução.',
                'cost' => '1po',
                'Weight' => null,
            ],
            // [
            //     'id' => 87,
            //     'item_name' => '',
            //     'item_type' => '',
            //     'description' => '',
            //     'cost' => '',
            //     'Weight' => '',
            // ],
        ];

            foreach($items as $item){
                Items::updateOrCreate(['id'=>$item['id']], $item);
            }
    }
}
