<?php

namespace Database\Seeders;

use App\Models\Weapons;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WeaponsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $weapons = [

            [
                'id' => 1,
                'weapon_name' => 'Adaga',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Acuidade, Leve, Arremesso (6m/18m)',
                'cost' => '2po',
                'Weight' => '0,5k',
            ],
            [
                'id' => 2,
                'weapon_name' => 'Cajado',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Versátil (1d8)',
                'cost' => '2pp',
                'Weight' => '2k',
            ],
            [
                'id' => 3,
                'weapon_name' => 'Clava Grande',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Duas Mãos',
                'cost' => '2pp',
                'Weight' => '5k',
            ],
            [
                'id' => 4,
                'weapon_name' => 'Desarmado',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => 'Especial',
                'description' => null,
                'properties' => null,
                'cost' => null,
                'Weight' => null,
            ],
            [
                'id' => 5,
                'weapon_name' => 'Foice Curta',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Leve',
                'cost' => '1po',
                'Weight' => '1k',
            ],
            [
                'id' => 6,
                'weapon_name' => 'Lança',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Versátil (1d8), Arremesso (6m/18m)',
                'cost' => '1po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 7,
                'weapon_name' => 'Maça',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => null,
                'cost' => '5po',
                'Weight' => '2k',
            ],
            [
                'id' => 8,
                'weapon_name' => 'Machadinha',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Leve, Arremesso (6m/18m)',
                'cost' => '5po',
                'Weight' => '1k',
            ],
            [
                'id' => 9,
                'weapon_name' => 'Martelo Leve',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Leve, Arremesso (6m/18m)',
                'cost' => '2po',
                'Weight' => '1k',
            ],
            [
                'id' => 10,
                'weapon_name' => 'Porrete',
                'weapon_type' => 'Simples Corpo-a-Corpo',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Leve',
                'cost' => '1pp',
                'Weight' => '1k',
            ],
            [
                'id' => 11,
                'weapon_name' => 'Arco Curto',
                'weapon_type' => 'Simples à Distância',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Distância (24m/96m), Munição, Duas mãos',
                'cost' => '25po',
                'Weight' => '1k',
            ],
            [
                'id' => 12,
                'weapon_name' => 'Azagaia',
                'weapon_type' => 'Simples à Distância',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Arremesso (9m/36m)',
                'cost' => '5pp',
                'Weight' => '1k',
            ],
            [
                'id' => 13,
                'weapon_name' => 'Beste Leve',
                'weapon_type' => 'Simples à Distância',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Distância (24m/96m), Munição, Recarga, Duas mãos',
                'cost' => '25po',
                'Weight' => '2,5k',
            ],
            [
                'id' => 14,
                'weapon_name' => 'Dardo',
                'weapon_type' => 'Simples à Distância',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Arremesso (6m/18m), Acuidade',
                'cost' => '5pc',
                'Weight' => '0,125k',
            ],
            [
                'id' => 15,
                'weapon_name' => 'Funda',
                'weapon_type' => 'Simples à Distância',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Distância (9m/36m), Munição',
                'cost' => '1pp',
                'Weight' => null,
            ],
            [
                'id' => 16,
                'weapon_name' => 'Alabarda',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d10',
                'description' => null,
                'properties' => 'Pesada, Alcance, Duas mãos',
                'cost' => '20po',
                'Weight' => '3k',
            ],
            [
                'id' => 17,
                'weapon_name' => 'Chicote',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d4',
                'description' => null,
                'properties' => 'Acuidade, Alcance',
                'cost' => '2po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 18,
                'weapon_name' => 'Cimitarra',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Acuidade, Leve',
                'cost' => '25po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 19,
                'weapon_name' => 'Espada Curta',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Acuidade, Leve',
                'cost' => '10po',
                'Weight' => '1k',
            ],
            [
                'id' => 20,
                'weapon_name' => 'Espada de Duas Mãos',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '2d6',
                'description' => null,
                'properties' => 'Pesada, Duas mãos',
                'cost' => '50po',
                'Weight' => '3k',
            ],
            [
                'id' => 21,
                'weapon_name' => 'Espada Longa',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Versátil (1d10)',
                'cost' => '15po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 22,
                'weapon_name' => 'Florete',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Acuidade',
                'cost' => '25po',
                'Weight' => '1k',
            ],
            [
                'id' => 23,
                'weapon_name' => 'Glaive',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d10',
                'description' => null,
                'properties' => 'Pesada, Alcance, Duas mãos',
                'cost' => '20po',
                'Weight' => '3k',
            ],
            [
                'id' => 24,
                'weapon_name' => 'Lança de Montaria',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d12',
                'description' => null,
                'properties' => 'Alcance, Especial',
                'cost' => '10po',
                'Weight' => '3k',
            ],
            [
                'id' => 25,
                'weapon_name' => 'Maça Estrela',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => null,
                'cost' => '15po',
                'Weight' => '2k',
            ],
            [
                'id' => 26,
                'weapon_name' => 'Machado',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Versátil (1d10)',
                'cost' => '10po',
                'Weight' => '2k',
            ],
            [
                'id' => 27,
                'weapon_name' => 'Machado Grande',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d12',
                'description' => null,
                'properties' => 'Pesada, Duas mãos',
                'cost' => '30po',
                'Weight' => '3,5k',
            ],
            [
                'id' => 28,
                'weapon_name' => 'Mangual',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => null,
                'cost' => '10po',
                'Weight' => '1k',
            ],
            [
                'id' => 29,
                'weapon_name' => 'Marreta',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '2d6',
                'description' => null,
                'properties' => 'Pesada, Duas mãos',
                'cost' => '10po',
                'Weight' => '5k',
            ],
            [
                'id' => 30,
                'weapon_name' => 'Martelo de Guerra',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Versátil (1d10)',
                'cost' => '15po',
                'Weight' => '1k',
            ],
            [
                'id' => 31,
                'weapon_name' => 'Picareta de Guerra',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d8',
                'description' => null,
                'properties' => null,
                'cost' => '5po',
                'Weight' => '1k',
            ],
            [
                'id' => 32,
                'weapon_name' => 'Pique',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d10',
                'description' => null,
                'properties' => 'Pesada, Alcance, Duas mãos',
                'cost' => '5po',
                'Weight' => '9k',
            ],
            [
                'id' => 33,
                'weapon_name' => 'Tridente',
                'weapon_type' => 'Marcial Corpo-a-Corpo',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Arremesso (6m/18m), Versátil (1d8)',
                'cost' => '5po',
                'Weight' => '2k',
            ],
            [
                'id' => 34,
                'weapon_name' => 'Arco Longo',
                'weapon_type' => 'Marcial à Distância',
                'damage' => '1d8',
                'description' => null,
                'properties' => 'Distância (45m/180m), Munição, Pesada, Duas mãos',
                'cost' => '50po',
                'Weight' => '1k',
            ],
            [
                'id' => 35,
                'weapon_name' => 'Besta de Mão',
                'weapon_type' => 'Marcial à Distância',
                'damage' => '1d6',
                'description' => null,
                'properties' => 'Distância (9m/36m), Munição, Leve, Recarga',
                'cost' => '75po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 36,
                'weapon_name' => 'Besta Pesada',
                'weapon_type' => 'Marcial à Distância',
                'damage' => '1d10',
                'description' => null,
                'properties' => 'Distância (30m/120m), Munição, Pesada, Recarga, Duas mãos',
                'cost' => '50po',
                'Weight' => '9k',
            ],
            [
                'id' => 37,
                'weapon_name' => 'Rede',
                'weapon_type' => 'Marcial à Distância',
                'damage' => 'Especial',
                'description' => null,
                'properties' => 'Distância (1,5m/4,5m), Especial, Arremesso',
                'cost' => '1po',
                'Weight' => '1,5k',
            ],
            [
                'id' => 38,
                'weapon_name' => 'Zarabatana',
                'weapon_type' => 'Marcial à Distância',
                'damage' => '1 dano',
                'description' => null,
                'properties' => 'Distância (7,5m/30m), Munição, Recarga',
                'cost' => '10po',
                'Weight' => '0,5k',
            ],
            // [
            //     'id' => 39,
            //     'weapon_name' => '',
            //     'weapon_type' => '',
            //     'damage' => '',
            //     'description' => null,
            //     'properties' => '',
            //     'cost' => '',
            //     'Weight' => '',
            // ],
        ];

            foreach($weapons as $weapon){
                Weapons::updateOrCreate(['id'=>$weapon['id']], $weapon);
            }
    }
}
